subnet_cidr_block = "10.0.10.0/24"
vpc_cidr_block = "10.0.0.0/16"
avail_zone = "us-east-1a"
env_prefix = "dev"
my_ip = "0.0.0.0/0"
instance_type = "t2.micro"
key_pair = "ssh-key"
default_public_key_location = "~/.ssh/id_rsa.pub"